CREATE TABLE IF NOT EXISTS students (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nim VARCHAR(20),
    nama VARCHAR(100)
);

INSERT INTO students (nim, nama)
VALUES (
    'REPLACE_NIM',
    'REPLACE_NAME'
);
